Google's policy changes...
civicrm/civicrm-user-guide pull request #342
Opened 2018-07-12 05:40 UTC by marsh-circle

Also - not checked - but this may positively affect the "Usage Limits" paragraph at the end of this page. As it's all coming into effect now, I thought it worth raising, but a bit pushed for resource on testing it atm.
Sorry :(
Martin

2018-10-03 08:11 UTC, homotechsual requested changes
Looks good - however the Google API keys are supported.

2018-10-03 08:12 UTC, MikeyMJCO commented on docs/initial-set-up/mapping.md
> +    Some providers have usage limits on their Mapping and Geocoding APIs. If you go over the limits you may receive a overlimit error when trying to save an address. Currently there is no support for
**Suggestion:** change to:

> Some providers have usage limits on their Mapping and Geocoding APIs. If you go over the limits you may receive a over limit error when trying to save an address.

2018-10-07 11:11 UTC, John-B commented
It is also worth pointing out in the docs that Google have changed their policy so mapping will no longer work without an API key, and it is impossible to get an API key without enabling billing in your Google account.

2018-10-10 15:24 UTC, homotechsual commented
After thinking about this @John-B personally I feel it's down to the user to choose their geocoding/mapping provider and deal with the terms - if we put it into the docs we're commiting ourselves to explaining any future changes. Where do we stop and do we monitor other geocoders/mapping systems to the same extent?

2019-07-19 08:43 UTC, MikeyMJCO commented
@marsh-circle are you able to "unstick" this PR as per feedback above?

2019-10-06 14:47 UTC, MikeyMJCO commented
Closing in favour of #410

2019-10-06 14:47 UTC, closed without merging