Resolve #419 by adding emoticon notes in CiviMail and Token docs abou…
civicrm/civicrm-user-guide pull request #438
Opened 2020-04-17 21:34 UTC by seamuslee001

…t url tracking implications of personalised links

2020-04-20 10:25 UTC, homotechsual requested changes

2020-04-20 10:25 UTC, MikeyMJCO commented on docs/common-workflows/tokens-and-mail-merge.md
> +    Checksum urls will not be tracked within CiviMail url tracking as they are personalised to the recipient.
```suggestion
    Checksum URLs will not be tracked within CiviMail URL tracking as they are personalised to the recipient.
```

2020-04-20 10:25 UTC, MikeyMJCO commented on docs/email/mass-mailings-using-civimail.md
> +        If you include a checksum or any kind of personalised token in your url
```suggestion
        If you include a checksum or any kind of personalised token in your URL 
```

2020-04-20 10:25 UTC, MikeyMJCO commented on docs/email/mass-mailings-using-civimail.md
> +        e.g. "http://example.org/civicrm/mailing/view?reset=1&id={mailing.key}&cid={contact.contact_id}&{contact.checksum}"
```suggestion
        e.g. `http://example.org/civicrm/mailing/view?reset=1&id={mailing.key}&cid={contact.contact_id}&{contact.checksum}`
```

2020-04-20 10:25 UTC, MikeyMJCO commented on docs/email/mass-mailings-using-civimail.md
> +        Such urls will not be redirected so as able to be tracked / counted.
```suggestion
        Such URLs will not be redirected so are not able to be tracked / counted.
```

2020-05-15 21:34 UTC, seamuslee001 commented
@MikeyMJCO have finally got around to making the changes now for you

2020-05-15 22:18 UTC, merged