Add example for Checksum for Contribution Pages for Membership Renewals
civicrm/civicrm-user-guide pull request #455
Opened 2020-08-12 05:56 UTC by agileware-justin

Add example for Checksum for Contribution Pages for Membership Renewals

2020-08-12 06:56 UTC, homotechsual requested changes

2020-08-12 06:56 UTC, MikeyMJCO commented on docs/common-workflows/tokens-and-mail-merge.md
> +-   Drupal: `http://example.org/civicrm/contribute/transact?reset=1&id=IDNUMBER&{contact.checksum}&cid={contact.contact_id}&mid={membership.id}`
```suggestion
-   Backdrop/Drupal: `http://example.org/civicrm/contribute/transact?reset=1&id=IDNUMBER&{contact.checksum}&cid={contact.contact_id}&mid={membership.id}`
```

2020-08-17 23:26 UTC, agileware-justin commented
@MikeyMJCO ready to go mate!

2020-08-18 07:42 UTC, homotechsual approved these changes

2020-08-18 07:42 UTC, merged